_target_: mattergen.diffusion.diffusion_module.DiffusionModule
model: mattergen
corruption: csp

loss_fn:
  _target_: mattergen.common.loss.MaterialsLoss
  reduce: sum
  include_pos: True
  include_cell: True
  include_atomic_numbers: False
  weights:
    cell: 1.0
    pos: 0.1


pre_corruption_fn:
  _target_: mattergen.property_embeddings.SetEmbeddingType
  p_unconditional: 0.2
  dropout_fields_iid: false